version: "3"

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: storage-mngmnt
      POSTGRES_USER: storage-mngmnt
      POSTGRES_DB: store-mngmnt
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  node:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "4000:4000"
